name: Cypress E2E Tests

# Run this workflow on pull requests and on pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run preview  # Starts your Vite server in preview mode
          wait-on: http://localhost:4173  # Waits for the Vite server to be up
          wait-on-timeout: 60  # Timeout in seconds

      # Upload screenshots if tests fail
      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload videos for all test runs
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos