name: Cypress E2E Tests

# Run this workflow on pull requests and on pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.7.0'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run test:e2e
        env:
          # Set the URL of your app (if using a deployed URL for testing)
          CYPRESS_BASE_URL: http://localhost:4173